### ISSUE TITLE
ValueError: DigMontage is a only a subset of info. There are 2 channel positions not present in the DigMontage. The required channels are: ['Fc5', 'Fc6']

### ISSUE THREAD

**Issue by mayankja1n** [plcrodrigues/py.ALPHA.EEG.2017-GIPSA#1]
When trying to use the `_get_single_subject_data()` call, I get the error:

`ValueError: DigMontage is a only a subset of info. There are 2 channel positions not present in the DigMontage. The required channels are: ['Fc5', 'Fc6']`

This happens with both the provided sample code, and my own code

**Comment by mayankja1n** [comment]
I just turned off the montage and that seems to work for now

**Comment by gcattan** [comment]
Hello, 
This error seems related to mne implementation (see [revision](https://github.com/plcrodrigues/py.ALPHA.EEG.2017-GIPSA/commit/88f656f84e4f8648b0f957a92ecb0152996db59d#diff-019b0b29ef5a6c4afc582fd2ff9cb39cb2e1a313ab44d7bba94f12707880526e)).
The workaround consist of switching useMontagePosition to false when creating your instance of Alphawaves:

![image](https://user-images.githubusercontent.com/6229031/96597149-c7965780-12ed-11eb-8238-af687aaa6939.png)

`dataset_alpha = AlphaWaves(useMontagePosition=False)` (in [classification_wrapper](https://github.com/gcattan/EEG_UNIFIED_ACCESS/blob/master/server/classif/classification_wrapper.py))
