### ISSUE TITLE
Fatigue label cannot be found

### ISSUE THREAD

**Issue by bencsikb** [plcrodrigues/py.ALPHA.EEG.2017-GIPSA#4]
Hello!

In the description of the dataset it's mentioned that for each recording the age, genre and fatigue of the participant is provided. However, I couldn't find any examples in the code on how it can be extracted. I have also examined the raw data, but it's still not clear for me where it's stored. 

Could you please help me with that?

Cheers,
Blanka

**Comment by plcrodrigues** [comment]
Hi,

Thank you for your interest in our dataset.

You will find some explanation about age, genre, and fatigue in page 5 of [this](https://hal.archives-ouvertes.fr/hal-02086581) document. The files related to these metadata are available in this Zenodo repository (https://zenodo.org/record/2605110#.YubjlexByWB).

Hope it helps!

Pedro

**Comment by gcattan** [comment]
@bencsikb Feel free to re-open if your problem is not solved.
